plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'xyz.wodeapp.expo.linesdk'
version = '0.2.0'

android {
  namespace "xyz.wodeapp.expo.linesdk"
  defaultConfig {
    versionCode 1
    versionName "0.2.0"
    consumerProguardFiles 'consumer-proguard-rules.pro'
  }
  buildFeatures {
    buildConfig true
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation('com.linecorp.linesdk:linesdk:5.11.1') {
      exclude group: 'androidx.lifecycle', module: 'lifecycle-viewmodel-ktx'
      exclude group: 'androidx.lifecycle', module: 'lifecycle-extensions'
  }
  implementation 'com.google.code.gson:gson:2.8.5'
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1"
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1"
}
